name: Linux Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # 允许在 GitHub 网页端手动触发
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-22.04 # 对应 XRootD 官方支持的版本
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v6

    - name: Cache XRootD Build
      id: cache-xrootd
      uses: actions/cache@v5
      with:
        # 我们要缓存的目标目录
        path: deps/xrootd
        # 缓存的 Key。如果我们要升级 xrootd 版本，只需修改这里的字符串
        # key: ${{ runner.os }}-xrootd-v6.0.1-static-v1
        key: linux-xrootd-v6.0.1-static-v6

    - name: Install System Dependencies for XRootD
      # 只有当没有命中缓存时，才执行耗时的克隆和编译
      if: steps.cache-xrootd.outputs.cache-hit != 'true'
      # 安装 XRootD 编译所需的底层 C++ 依赖
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++ libssl-dev uuid-dev libxml2-dev zlib1g-dev

    - name: Build XRootD Static Libraries
      # 只有当没有命中缓存时，才执行耗时的克隆和编译
      if: steps.cache-xrootd.outputs.cache-hit != 'true'
      run: |
        echo "Cache miss. Building XRootD from source..."
        git clone --depth 1 --branch v6.0.1 https://github.com/xrootd/xrootd.git xrootd-src
        mkdir xrootd-src/build && cd xrootd-src/build/
        
        # ================= 黑魔法注入开始 =================
        # 在 project( XRootD ) 之后强行插入一个宏，将所有的 SHARED 覆盖为 STATIC
        sed -i '/project( XRootD )/a \
        macro(add_library name)\
          set(ARGS ${ARGN})\
          list(FIND ARGS "SHARED" idx)\
          if(idx GREATER -1)\
            list(REMOVE_AT ARGS ${idx})\
            list(INSERT ARGS ${idx} "STATIC")\
          endif()\
          _add_library(${name} ${ARGS})\
        endmacro()' ../CMakeLists.txt
        # ================= 黑魔法注入结束 =================
        
        cmake .. \
          -DCMAKE_INSTALL_PREFIX=${GITHUB_WORKSPACE}/deps/xrootd \
          -DBUILD_SHARED_LIBS=OFF \
          -DXRDCL_ONLY=ON \
          -DENABLE_SERVER=OFF \
          -DENABLE_PYTHON=OFF \
          -DCMAKE_CXX_STANDARD=17 \
          -DCMAKE_POSITION_INDEPENDENT_CODE=ON
          
        make -j$(nproc)
        make install
        # 编译完成后清理源码，节省缓存空间
        cd ../..
        rm -rf xrootd-src

    - uses: pnpm/action-setup@v5
    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: '26'
        cache: 'pnpm'


    - name: Install NPM Dependencies & Build TypeScript
      run: pnpm install

    - name: Build Node Addon (node-gyp)
      # 手动触发 C++ 扩展编译，使用刚刚编译好的 XRootD 静态库
      run: pnpm run build:addon

    # - name: Run Tests
    #   # 跑你的 Jest 测试用例
    #   run: pnpm test